doctrine:
    dbal:
        dbname: kpiraspinu
        host: mysql
        port: 3306
        user: root
        password: 123456
        server_version: 10.5.9
        driver: pdo_mysql
        url: '%env(resolve:DATABASE_URL)%'

        charset: UTF8
        types:
            record_id:
                class: App\Products\Music\Record\Infrastructure\Doctrine\Persistence\Type\RecordIdType
            artist_id:
                class: App\Products\Music\Artist\Infrastructure\Doctrine\Persistence\Type\ArtistIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            record:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Products/Music/Record/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Products\Music\Record\Domain'
                alias: App
            artist:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Products/Music/Artist/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Products\Music\Artist\Domain'
                alias: App

