doctrine:
    dbal:
        dbname: kpiraspinu
        host: mysql
        port: 3306
        user: root
        password: 123456
        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        server_version: '8'
        charset: UTF8
        types:
            record_id:
                class: App\Products\Music\Record\Infrastructure\Doctrine\Persistence\Type\RecordIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Record:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Products/Music/Record/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Products\Music\Record\Domain'
                alias: App


